### ISSUE TITLE
Websocket for subscriptions won't connect

### ISSUE THREAD

**Issue by charlieroth** [howtographql/graphql-js#1]
Whenever I try to create a subscription for Link and then perform a createLink mutation. Nothing happens in the subscription tab when I expect to see a subscription to be logged. When I opened the console I noticed this.

```
WebSocket connection to 'ws://locahost:3000/subscriptions' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```

and it will continuously attempt to reconnect and fail every time.

Here is a link to my repo if anyone could help me [https://github.com/charlieroth/howtogql-node](https://github.com/charlieroth/howtogql-node). I followed the tutorial step for step and went back through multiple times and checked my code and couldn't find anything wrong.

**Comment by mairatma** [comment]
@charlieroth I've just checked this and it seems like it was just a small typo in your code when specifying the url. In the error message itself you can see that it's saying `ws://locahost:3000/subscriptions` instead of `ws://localhost:3000/subscriptions` (missing an `l` inside `localhost`). I've tried running your code with [this line](https://github.com/charlieroth/howtogql-node/blob/master/src/index.js#L36) fixed and it worked as expected 😄

**Comment by mairatma** [comment]
Can you double check if replacing that fixes it for you too? If so you can close the issue :)

**Comment by charlieroth** [comment]
@mairatma thanks it worked. I obviously didn't look hard enough 😂

**Comment by marktani** [comment]
That was a great catch @mairatma 😄
