### ISSUE TITLE
Subscriptions not showing new additions to the database

### ISSUE THREAD

**Issue by tlgreg86** [howtographql/graphql-js#14]
I went through the tutorial and am able to perform queries and mutations on it but when I run subscription in the playground it doesn't output new anything when I add new links to the database. I removed the where filter and it still doesn't work. Considering everything else works this seems to be an issue with the tutorial.

**Comment by AliceSum** [comment]
Same with me! :D

**Comment by nikolasburk** [comment]
Thanks for reporting this @tlgreg86 and @JonathanSum! Apparently there were some underlying issues in how subscriptions were handled in `graphql-yoga` and `graphql-tools`. I'll take a look today and keep you posted here!

**Comment by nikolasburk** [comment]
So, the problem is due to this issue: https://github.com/graphcool/prisma/issues/1734

I temporarily added a fix by passing an empty filter to the subscription resolvers: https://github.com/howtographql/graphql-js/blob/master/src/resolvers/Subscription.js

I will update it again once the issue is fixed.
