### ISSUE TITLE
"message": "Cannot return null for non-nullable field Mutation.post."

### ISSUE THREAD

**Issue by AliceSum** [howtographql/graphql-js#16]
I was trying to post a post with login token
as this https://www.howtographql.com/graphql-js/5-applying-authentication/

my code:https://github.com/JonathanSum/GraphqlNote

Error Picture:
https://imgur.com/a/Ffxga

**Comment by AliceSum** [comment]
I am so sorry.

**Comment by marktani** [comment]
Why did you close this? What was your resolution? 🙂

**Comment by nelsonBlack** [comment]
mostly caused by defining your graphql datatypes with the "!" non null attribute ..make sure you dont have the "!"
`type clients {
  clientId: Int !//returns error when you return object after mutation
  firstName: String
  lastName: String
  clientResidence: String
  clientEmail: String
  clientNumber: String
  clientJoinDate: String
  createdAt: String
  updatedAt: String
  radio:Int
  
}`
