### ISSUE TITLE
prisma deploy did not work

### ISSUE THREAD

**Issue by lynnic26** [howtographql/graphql-js#28]
when I followed code on the tutorial, and run `prisma deploy`
the console shows
```
Cluster undefined does not exist.
```
Is this about the prisma version ?
I use prisma 1.8.3, while the tutorial is prisma 1.6

**Comment by marktani** [comment]
Can you please additionally share your `prisma.yml` file and the `~/.prisma/config.yml` file? **Please remove all sensitive information before sharing it here**. For example, the `config.yml` file contains a `cloudSessionKey` which shouldn't be shared.

**Comment by nikolasburk** [comment]
Hey @lynnic26, thanks a lot for opening this issue! It's indeed because you're running a newer version of the Prisma CLI. The tutorial will be updated soon (in fact, @christiannwamba is currently working on that update). 

In the meanwhile, please make sure to use Prisma 1.6 when going through the tutorial as it is currently instructed on [this](https://www.howtographql.com/graphql-js/4-adding-a-database/) page 🙂 

![image](https://user-images.githubusercontent.com/4058327/41112376-098ff44e-6a7f-11e8-969c-d1432596eb16.png)
