### ISSUE TITLE
Update README: add info about starting MongoDB. 

### ISSUE THREAD

**Issue by fuzinato** [howtographql/graphql-js#7]
After following README instruction I get an error:
```
(node:19472) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect toserver [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
(node:19472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections thatare not handled will terminate the Node.js process with a non-zero exit code.
```
Would be nice to add info about starting DB service prior to running the server

**Comment by nikolasburk** [comment]
Hi @fuzinato! My sincere apologies for the delay of responding to your issue - unfortunately I wasn't able to put in much maintenance effort into How To GraphQL over the past months. However, I have just started a major cleanup and am taking a look at all issues.

The issue should have been fixed with the latest update of the `graphql-js` tutorial. Please let me know if you're running into further issues 🙂
