### ISSUE TITLE
Cannot GET /graphiql 

### ISSUE THREAD

**Issue by MahmoudBakry** [howtographql/graphql-js#9]
I follow the tutorial until reaching to authentication lesson but in middle  of it when we make Authenticating requests and Linking User to created links and run the server , It run correctly but when i go my browser 
by the endpoint url "http://localhost:3000/graphiql" , I get this error 

Cannot GET /graphiql

![screenshot from 2017-11-19 19-33-35](https://user-images.githubusercontent.com/24420403/32993438-96b36016-cd60-11e7-95c9-0dbf1edffa58.png)

**Comment by epitaphmike** [comment]
It seems you are missing the "graphiql" route. The information is displayed in Step 3 of "Configuring Graphiql headers"
[https://www.howtographql.com/graphql-js/5-authentication/](url)

```
app.use('/graphql', bodyParser.json(), graphqlExpress(buildOptions));

app.use('/graphiql', graphiqlExpress({
    endpointURL: '/graphql',
    passHeader: `'Authorization': 'bearer token-foo@bar.com'`,
}));
```

**Comment by nikolasburk** [comment]
Hi @MahmoudBakry ! My sincere apologies for the delay of responding to your issue - unfortunately I wasn't able to put in much maintenance effort into How To GraphQL over the past months. However, I have just started a major cleanup and am taking a look at all issues.

The issue should have been fixed with the latest update of the `graphql-js` tutorial. Please let me know if you're running into further issues 🙂
